# defaults for all profiles
[profile.default]
gas_reports = ["*"]
# auto_detect_solc = true
optimizer = true
optimizer_runs = 1000000
verbosity = 3

[profile.ci]
fuzz_runs = 10000
fuzz_max_local_rejects = 2048
fuzz_max_global_rejects = 16777215
